apiVersion: v1
kind: Service
metadata:
  name: ruby-service
spec:
  # this type is loadbalancer for high availability
  type: LoadBalancer
  selector:
    app: ruby
  ports:
    - port: 80
      targetPort: 80
